### ISSUE TITLE
ImportError: No module named gpuarray.type

### ISSUE THREAD

**Issue by YuQingL** [kahst/AcousticEventDetection#1]
Hello,   @kahst 
Thank you for your package though I am still not able to use it.
I followed you installation instruction and downloaded pre-trained model:"sh model/fetch_model.sh". When I executed script:"python AED_test.py --filenames 'dataset/schreien_scream.wav' --modelname 'AED_Example_Run_model.pkl' --overlap 4 --results 5 --confidence 0.01", the following error occurred:

scu@scu-desktop:~/AcousticEventDetection$ python AED_test.py --filenames 'dataset/schreien_scream.wav' --modelname 'AED_Example_Run_model.pkl' 
HANDLING IMPORTS...
Using gpu device 0: GeForce GTX 960 (CNMeM is disabled, CuDNN 7004)
/usr/local/lib/python2.7/dist-packages/theano/sandbox/cuda/__init__.py:600: UserWarning: Your CuDNN version is more recent then Theano. If you see problems, try updating Theano or downgrading CuDNN to version 4.
  warnings.warn(warn)
...DONE!
IMPORTING MODEL...
Traceback (most recent call last):
  File "AED_test.py", line 156, in <module>
    NET, CLASSES, IM_SIZE, IM_DIM = loadModel(TRAINED_MODEL)
  File "AED_test.py", line 57, in loadModel
    data = pickle.load(f)
  File "/usr/lib/python2.7/pickle.py", line 1378, in load
    return Unpickler(file).load()
  File "/usr/lib/python2.7/pickle.py", line 858, in load
    dispatch[key](self)
  File "/usr/lib/python2.7/pickle.py", line 1090, in load_global
    klass = self.find_class(module, name)
  File "/usr/lib/python2.7/pickle.py", line 1124, in find_class
    __import__(module)
ImportError: No module named gpuarray.type

I have installed Python 2.7,python-opencv,numpy,scipy,scikit-learn,python_speech_features,pydub,matplotlib,cuda8.0,cuDNN7,Thenao 0.8,Lasagne  on Ubuntu 14.04.

As a beginner,I'm sorry to trouble you.Can you help me?Thanks!

**Comment by kahst** [comment]
I'm not sure why this might happen. I have to do some research to find out what's going on there. It could be caused by the CuDNN 7 version you are using, maybe you should indeed try downgrading to another version (I'm using CuDNN 5110). 

What happens if you train and save a model and try to import that model afterwards? Does it still crash?

**Comment by YuQingL** [comment]
Hello,@kahst 
Thank you for your reply!  The incompatibility  of the version of Thenao and cuda lead to this error .  At the beginning,I downgraded  CuDNN7 to CuDNN5, but the same error still occurred.  Then I upgraded Thenao,this error no longer appears.   Now, I train and save a model and try to import that model afterwards, everything is going well.

**Comment by lancegon** [comment]
Hello,@YuQingL
> Thank you for your reply! The incompatibility of the version of Thenao and cuda lead to this error . At the beginning,I downgraded CuDNN7 to CuDNN5, but the same error still occurred. Then I upgraded Thenao,this error no longer appears. Now, I train and save a model and try to import that model afterwards, everything is going well.

I got the same trouble, could you tell me which Theano you used when you solve this problem?
