### ISSUE TITLE
ValueError: all the input arrays must have same number of dimensions

### ISSUE THREAD

**Issue by Jackaryyy** [kahst/AcousticEventDetection#2]
Hello kahst,
Thanks for sharing the model!
I got some trouble while using your model.
I followed your instruction and download the public data set "UrbanSound8K", when I use AED_spec.py to extract the spectrograms of wav files, python shell reports:

NUMBER OF EVENTS: 10
dataset/UrbanSound8K/audio/fold1/event0_air_conditioner/134717-0-0-0.wav
SAMPLE RATE: 44100
0 ERROR
Traceback (most recent call last):
  File "E:\python\python364\project\AcousticEventDetection-master\AED_spec_new.py", line 137, in <module>
    for spec in getMultiSpec(wav):
  File "E:\python\python364\project\AcousticEventDetection-master\AED_spec_new.py", line 111, in getMultiSpec
    magspec = getSpecFromSignal(sig, rate, seconds)
  File "E:\python\python364\project\AcousticEventDetection-master\AED_spec_new.py", line 58, in getSpecFromSignal
    frames = psf.sigproc.framesig(sig, winlen*rate, winstep*rate, winfunc)
  File "E:\python\python364\lib\site-packages\python_speech_features\sigproc.py", line 33, in framesig
    padsignal = numpy.concatenate((sig,zeros))
ValueError: all the input arrays must have same number of dimensions
dataset/UrbanSound8K/audio/fold1/event0_air_conditioner/134717-0-0-1.wav
SAMPLE RATE: 44100
0 ERROR
Traceback (most recent call last):
  File "E:\python\python364\project\AcousticEventDetection-master\AED_spec_new.py", line 137, in <module>
    for spec in getMultiSpec(wav):
  File "E:\python\python364\project\AcousticEventDetection-master\AED_spec_new.py", line 111, in getMultiSpec
    magspec = getSpecFromSignal(sig, rate, seconds)
  File "E:\python\python364\project\AcousticEventDetection-master\AED_spec_new.py", line 58, in getSpecFromSignal
    frames = psf.sigproc.framesig(sig, winlen*rate, winstep*rate, winfunc)
  File "E:\python\python364\lib\site-packages\python_speech_features\sigproc.py", line 33, in framesig
    padsignal = numpy.concatenate((sig,zeros))
ValueError: all the input arrays must have same number of dimensions
...

I can only extract a few files.
So do you know where is wrong? Could you help me with this problem? I'm really sorry to bother you. Thanks！
Best regards!

**Comment by kahst** [comment]
I'm actually not sure what might cause this error. It seems like python_speech_features can't extract the spectrogram of certain files. Maybe there was a problem with opening the files and the 'sig' variable is empty. You could try to 'print sig.shape' before it's passed to 'getSpecFromSignal' to see if it's empty or None. If thats the case, we have to dig a bit deeper and figure out why psf can't open the files.

**Comment by Jackaryyy** [comment]
Thanks for replying！
I've tried to print sig.shape, it turns out to be (176400, 2). I think it should be (176400,) after reading the code of "python_speech_features\sigproc.py", it seems that all the signal process functions assume the signal is one dimension, for example, there are two statements in sigproc.py:
    slen = len(sig)
    zeros = numpy.zeros((padlen - slen,)
    padsignal = numpy.concatenate((sig,zeros))
the input of numpy.concatenate function must have the same dimension

**Comment by Jackaryyy** [comment]
Thanks for replying！
I've tried to print sig.shape, it turns out to be (176400, 2). I think it should be (176400,) after reading the code of "python_speech_features\sigproc.py", it seems that all the signal process functions assume the signal is one dimension, for example, there are two statements in sigproc.py:
slen = len(sig)
zeros = numpy.zeros((padlen - slen,)
padsignal = numpy.concatenate((sig,zeros))
the input of numpy.concatenate function must have the same dimension.
Thanks!

**Comment by kahst** [comment]
So it's probably a stereo recording and you need to condense it to mono. This might be possible with PSF - if not, you can simply check if there is a second dimension and just remove it.
